version: "3.2"
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
    - "80:8080"
    - "50000:50000"
    volumes:
    - ./jenkins_data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always
